### ISSUE TITLE
Using a packet asset in html

### ISSUE THREAD

**Issue by lebogan** [busyloop/rucksack#5]
Seriously, this shard is awesome. I am using it to generate web frameworks with Kemal.
Is there a way to reference image files included in an html file. I use slang for my views.
```
img src=<prepacked image file>
```
I can't quite figure out the phrasing. This doesn't work.
```
img src=rucksack("./public/images/logo.png").read(STDOUT)
```

Thanks for publishing this shard.

**Comment by m-o-e** [comment]
Thanks!

I'm unfortunately not familiar with slang but I believe the following might work:

* `img src=rucksack("./public/images/logo.png").path[1..-1]` to pack the file and get the path as String
   without the leading dot
* Ensure the webserver actually serves the files, as seen in the README example, e.g. somewhere in your request handler:
  `rucksack("." + path).read(context.response.output)` to re-add the leading dot, read the file from rucksack
   and write it to the HTTP response

However, I'm not sure whether slang allows macros in its templates and what syntax for them would be.

As a potential alternative you could perhaps pack _all_ files under `./public/images`
with a "find"-macro as seen in the README and then just reference them normally in the template.
(less elegant as it would then also pack files that are not referenced in any template - but at least
this latter method will definitely work)

**Comment by lebogan** [comment]
I tried packing all the files with the find macro and tried to reference one:
```
img src="./public/images/logo.png"
```
I just get the little missing image icon and not the image.  My log file shows:
```
GET /public/images/logo.png 397.67us
```
As this is not an issue with the shard but with my code, I think maybe I need to rethink the whole thing. Everything else I'm doing with rucksack works just fine.

Thanks again for all your help.

**Comment by lebogan** [comment]
Ok, so this is not very elegant but it works:
```
File.open("/tmp/logo.png", "w") { |file| rucksack("./public/images/logo.png").read(file) }
```
Then:
```
img src=/tmp/logo.png
```
Kinda defeats the whole purpose of rucksack;-) Oh well. I will close this if no further comments.
Thanks

**Comment by lebogan** [comment]
Ok my stupid. Kemal knows about the public folder so `img src="/images/logo.png` works as advertised.

**Comment by m-o-e** [comment]
Awesome, glad to hear it worked out! 👍
